config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'

  resources :users, only: [:index,:show,:update] , param: :name do
    collection do
      get :check_email
      get :check_name
    end
    member do
      get :following
      get :followers
    end
    resources :activities, only:[:index] do
      collection do
        get :following
        get :followers
      end
    end
  end

  resources :tweets, only: [:index,:create] do
    collection do
      delete :destroy
    end
  end

  resources :follow_relationships, only: [:create] do
    collection do
      delete :destroy
    end
  end

  resources :retweet_relationships, only: [:create] do
    collection do
      delete :destroy
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_activities.html.haml
.activities-container
  = high_chart("chart-1", @graph_data_date)
  = high_chart("chart-2", @graph_data_day)
  = high_chart("chart-3", @graph_data_period)

app/views/layouts/_main.html.haml
.page-outer
  -if @tweet.errors.any?
    .alert-messages
      .message
        %a.close{href: ""}
          %i.fa.fa-times
        - @tweet.errors.full_messages.each do |msg|
          %span.message-text= msg
  -if notice
    .alert-messages
      .message
        %a.close{href: ""}
          %i.fa.fa-times
        %span.message-text= notice
  #page-container.AppContent.clearfix
    .dashboard
      .DashboardProfileCard
        = link_to(user_path(current_user), class: "DashboardProfileCard-bg u-bgUserColor") do
          - if current_user.image_canopy.present? then
            = image_tag(current_user.image_canopy.url, size: "288x95")
        .DashboardProfileCard-content
          .DashboardProfileCard-avatarContainer
            .avatar-settings
              = link_to user_path(current_user), class: "DashboardProfileCard-avatarLink" do
                - if current_user.image_avatar.present? then
                  = image_tag(current_user.image_avatar.url, class: "DashboardProfileCard-avatarImage")
                - else
                  .DashboardProfileCard-avatarImage.u-bgUserColor
                    %i.fa.fa-camera
          .DashboardProfileCard-userFields
            .DashboardProfileCard-name
              = link_to current_user.nickname, user_path(current_user), class: "u-textInheritColor"
            %span.DashboardProfileCard-screenname.u-inlineBlock
              = link_to user_path(current_user), class: "DashboardProfileCard-screennameLink" do
                %b.username
                  = "@" + current_user.name
          .ProfileCardStats
            %ul.ProfileCardStats-statList.Arrange.Arrange--bottom.Arrange-equal
              %li.ProfileCardStats-stat.Arrange-sizeFit
                = link_to(user_path(current_user), class: "ProfileCardStats-statLink u-textUserColor u-linkClean u-block") do
                  %span.ProfileCardStats-statLabel.u-block
                    ツイート
                  %span.ProfileCardStats-statValue
                    = current_user.tweets_count
              %li.ProfileCardStats-stat.Arrange-sizeFit
                = link_to(following_user_path(current_user), class: "ProfileCardStats-statLink u-textUserColor u-linkClean u-block") do
                  %span.ProfileCardStats-statLabel.u-block
                    フォロー
                  %span.ProfileCardStats-statValue#follows_count
                    = current_user.follows_count
              %li.ProfileCardStats-stat.Arrange-sizeFit
                = link_to(followers_user_path(current_user), class: "ProfileCardStats-statLink u-textUserColor u-linkClean u-block") do
                  %span.ProfileCardStats-statLabel.u-block
                    フォロワー
                  %span.ProfileCardStats-statValue
                    = current_user.followers_count
      .module
        .flex-module
          .flex-module-header
            %h3 ユーザーリスト
          .DashboardUserList
            %ol
              - User.all.each do |user|
                %li.DashboardUserList-item
                  .content
                    = link_to(user_path(user), class: "account-group", data_user_id: user.id) do
                      - if user.image_avatar.present? then
                        = image_tag(user.image_avatar.url, size: "48x48", class: "avatar")
                      - else
                        = image_tag("default_profile_normal.png",size: "48x48", class: "avatar")
                      %span.account-group-inner
                        %strong.fullname= user.nickname
                        %span.username= "@" + user.name
                    - if current_user != user then
                      .user-actions
                        %div{ class: current_user.following?(user) ? "following-button-wrapper" : "follow-button-wrapper"}
                          = form_tag(follow_relationships_path, method: :post, class: "follow-button") do
                            = hidden_field_tag :follow_to_id, user.id
                            = submit_tag("フォローする", class: "EdgeButton EdgeButton--secondary EdgeButton--small")
                          = form_tag(follow_relationships_path, method: :delete, class: "following-button") do
                            = hidden_field_tag :follow_to_id, user.id
                            = submit_tag("フォロー中", class: "EdgeButton EdgeButton--primary EdgeButton--small")

    .content-main.top-timeline-tweetbox
      .timeline-tweet-box
        .home-tweet-box
          - if current_user.image_avatar.present? then
            = image_tag(current_user.image_avatar.url,size: "32x32", class: "top-timeline-tweet-box-user-image")
          - else
            = image_tag("default_profile_normal.png",size: "32x32", class: "top-timeline-tweet-box-user-image")
          = form_for(@tweet, html:{class: "t1-form clearfix"}) do |f|
            .tweet-content
              .editor-container
                = f.text_area :tweet, autofocus: false, class: "editor", maxlength: "240", placeholder: "いまどうしてる？"
            .tweetboxtoolbar
              .TweetBoxExtras
                .TweetBoxExtras-item
                  = f.file_field :image, autocomplete: "false"
                  %button#tweet-image-choose-button
                    %i.fa.fa-picture-o
              .tweetboxtoolbar-tweetButton
                = f.submit "ツイート", class: "EdgeButton EdgeButton--medium EdgeButton--primary2"
      = render "layouts/tweets_stream"

app/views/layouts/_mypage.html.haml
-if @user.errors.any?
  .alert-messages
    .message
      %a.close{href: ""}
        %i.fa.fa-times
      - @user.errors.full_messages.each do |msg|
        %span.message-text= msg
#profile-container.AppContent.clearfix
  .ProfilePage-editingOverlay
  = form_for(@user) do |f|
    .ProfileCanopy.ProfileCanopy--withnav.ProfileCanopy--large
      .ProfileCanopy--inner
        .ProfileCanopy-header.u-bgUserColor
          .ProfileCanopy-headerBg
            - if @user.image_canopy.present? then
              = image_tag(@user.image_canopy.url)
          .ProfileHeaderEditing
            .ProfileHeaderEditing-overlay
            %button.ProfileHeaderEditing-button
              .ProfileHeaderEditing-addHeaderHelp
                - if current_user.image_canopy.present? then
                  %i.fa.fa-picture-o
                  %p ヘッダー画像を変更する
                - else
                  %i.fa.fa-camera
                  %p ヘッダー画像を追加する
            #choose-header-container
              #choose-header.dropdown.center
                .uploader-image.clearfix
                  .dropdown-menu#header-dropdown-menu
                    .dropdown-caret
                      .caret-outer
                        %i.fa.fa-caret-up
                      .caret-inner
                        %i.fa.fa-caret-up
                    %ul
                      %li#header-choose-new
                        = f.file_field :image_canopy, autocomplete: "false"
                        %button#header-choose-button.dropdown-link
                          画像をアップロード
                      - if current_user.image_canopy.present? then
                        %li#header-choose-new
                          = f.check_box :remove_image_canopy
                          %button#header-drop-button.dropdown-link
                            削除
                      %li.dropdown-divider
                      %li#header-cancel-option
                        %button#header-cancel-button.dropdown-link
                          キャンセル
          .AppContainer
            .ProfileCanopy-avatar
              .ProfileAvatar.u-bgUserColor
                - if @user.image_avatar.present? then
                  = image_tag(@user.image_avatar.url, class: "ProfileAvatar-image")
                - elsif @user.id == current_user.id then
                  = image_tag("owner_empty_avatar.png", class: "ProfileAvatar-image")
                - else
                  = image_tag("default_profile_normal.png", class: "ProfileAvatar-image")
              .ProfileAvatarEditing
                - if current_user.image_avatar.present? then
                  = image_tag(current_user.image_avatar.url, class: "ProfileAvatarEditing-placeholder")
                -else
                  .ProfileAvatarEditing-placeholder.u-bgUserColor
                .ProfileAvatarEditing-overlay
                %button.ProfileAvatarEditing-button
                  .ProfileAvatarEditing-addAvatarHelp
                    - if current_user.image_avatar.present? then
                      %i.fa.fa-picture-o
                      %p プロフィール画像を変更
                    - else
                      %i.fa.fa-camera
                      %p プロフィール画像を追加
                #choose-photo.dropdown.center
                  .uploader-image.clearfix
                    .dropdown-menu#avatar-dropdown-menu
                      .dropdown-caret
                        .caret-outer
                          %i.fa.fa-caret-up
                        .caret-inner
                          %i.fa.fa-caret-up
                      %ul
                        %li#photo-choose-new
                          = f.file_field :image_avatar, autocomplete: "false"
                          %button#avatar-choose-button.dropdown-link
                            画像をアップロード
                        - if current_user.image_avatar.present? then
                          %li#photo-choose-new
                            = f.check_box :remove_image_avatar
                            %button#avatar-drop-button.dropdown-link
                              削除
                        %li.dropdown-divider
                        %li#cancel-option
                          %button#avatar-cancel-button.dropdown-link
                            キャンセル
        .ProfileCanopy-navbar.u-boxShadow
          .ProfilePage-editingOverlay
          .AppContainer
            .Grid.Grid--withGutter
              .Grid-cell.u-size1of3
              .Grid-cell.u-size2of3
                .ProfileNav
                  %ul.ProfileNav-list
                    %li{ class: (page == "tweet") ? "ProfileNav-item ProfileNav-item--tweets isActive" : "ProfileNav-item ProfileNav-item--tweets"}
                      = link_to(user_path(@user), class: "ProfileNav-stat u-textCenter") do
                        %span.ProfileNav-label ツイート
                        %span.ProfileNav-value= @user.tweets_count
                    %li{ class: (page == "following") ? "ProfileNav-item ProfileNav-item--following isActive" : "ProfileNav-item ProfileNav-item--following"}
                      = link_to(following_user_path(@user), class: "ProfileNav-stat u-textCenter") do
                        %span.ProfileNav-label フォロー
                        %span.ProfileNav-value#follows_count= @user.follows_count
                    %li{ class: (page == "followers") ? "ProfileNav-item ProfileNav-item--follower isActive" : "ProfileNav-item ProfileNav-item--follower"}
                      = link_to(followers_user_path(@user), class: "ProfileNav-stat u-textCenter") do
                        %span.ProfileNav-label フォロワー
                        %span.ProfileNav-value#followers_count= @user.followers_count
                    %li{ class: (page == "activities") ? "ProfileNav-item ProfileNav-item--activities isActive" : "ProfileNav-item ProfileNav-item--activities"}
                      = link_to(user_activities_path(@user), class: "ProfileNav-stat u-textCenter ProfileNav-stat--activities") do
                        %span.ProfileNav-value.activities
                          アクティビティ
                    %li.ProfileNav-item.ProfileNav-item--userActions.u-floatRight.u-textRight
                      .UserActions
                        - if user_signed_in? && current_user.id == @user.id
                          %button.EdgeButton.EdgeButton--medium.EdgeButton--tertiary#ProfileEditButton
                            プロフィールを編集
                        - else
                          %div{ class: current_user.following?(@user) ? "following-button-wrapper" : "follow-button-wrapper"}
                            .follow-button
                              = hidden_field_tag :follow_to_id, @user.id
                              %button.EdgeButton.EdgeButton--secondary.EdgeButton--medium.counterpart
                                フォローする
                            .following-button
                              = hidden_field_tag :follow_to_id, @user.id
                              %button.EdgeButton.EdgeButton--primary.EdgeButton--medium.counterpart
                                フォロー中
                        .ProfilePage-editingButtons
                          %button.EdgeButton.EdgeButton--medium.EdgeButton--tertiary#ProfileEditCancelButton
                            キャンセル
                          = f.submit "変更を保存", class: 'EdgeButton EdgeButton--medium EdgeButton--secondary'
    .AppContainer
      .AppContent-main
        .Grid.Grid--withGutter
          .Grid-cell.u-size1of3
            .Grid.Grid--withGutter
              .Grid-cell
                .ProfileSidebar.ProfileSidebar-withLeftAlignment
                  .ProfileHeaderCard
                    %h1.ProfileHeaderCard-name
                      = @user.nickname
                    %h2.ProfileHeaderCard-screenname.u-inlineBlock
                      = "@" + @user.name
                    %p.ProfileHeaderCard-bio
                      = @user.biography
                  .ProfileHeaderCardEditing.u-bgColorLightest
                    .ProfileHeaderCardEditing-name.ProfileHeaderCardEditing-item
                      = f.text_field :nickname, autofocus: true, class: "ProfileHeaderCardEditing-editableField u-borderUserColorLight", maxlength: "50", placeholder: "名前"
                    .ProfileHeaderCardEditing-screenname.u-textUserColor
                      = "@" + @user.name
                    .ProfileHeaderCardEditing-bio.ProfileHeaderCardEditing-item
                      = f.text_area :biography, autofocus: true, class: "ProfileHeaderCardEditing-editableField u-borderUserColorLight", placeholder: "自己紹介"

          .Grid-cell.u-size2of3
            .Grid.Grid--withGutter
              .Grid-cell
                .ProfileHeading
                  .ProfileHeading-spacer
                  .ProfileHeading-content
                    - if page == "tweet" then
                      %ul.ProfileHeading-toggle
                        %li.ProfileHeading-toggleItem.is-active
                          %span ツイート
                    - if page == "activities" then
                      %ul.ProfileHeading-toggle
                        %li.ProfileHeading-toggleItem
                          = link_to(user_activities_path(@user), class: page2 == "user" ? "ProfileHeading-toggleLink isActive" : "ProfileHeading-toggleLink") do
                            %span ユーザー
                        %li.ProfileHeading-toggleItem
                          = link_to(following_user_activities_path(@user), class: page2 == "following" ? "ProfileHeading-toggleLink isActive" : "ProfileHeading-toggleLink") do
                            %span フォロー
                        %li.ProfileHeading-toggleItem
                          = link_to(followers_user_activities_path(@user), class: page2 == "followers" ? "ProfileHeading-toggleLink isActive" : "ProfileHeading-toggleLink") do
                            %span フォロワー
                .ProfileTimeline#timeline
                  - if page == "tweet" then
                    = render "layouts/tweets_stream"
                  - elsif page == "activities" then
                    = render "layouts/activities"
                  - else
                    = render "layouts/mypage_user_list"

app/views/layouts/_mypage_user_list.html.haml
.Grid.Grid--withGutter.usercell
  - @users.each do |user|
    .Grid-cell.u-size1of2.u-mb10.u-floatLeft
      .ProfileCard
        = link_to(user_path(user), class: "ProfileCard-bg u-bgUserColor") do
          - if user.image_canopy.present? then
            = image_tag(user.image_canopy.url, size: "285x90")
        .ProfileCard-content
          = link_to(user_path(user), class: "ProfileCard-avatarLink") do
            - if user.image_avatar.present? then
              = image_tag(user.image_avatar.url, size: "70x70", class: "ProfileCard-avatarImage")
            - else
              = image_tag("default_profile_normal.png",size: "70x70", class: "ProfileCard-avatarImage")
          .ProfileCard-actions
            .UserActions
              - if user.id != current_user.id then
                %div{ class: current_user.following?(user) ? "following-button-wrapper" : "follow-button-wrapper"}
                  .follow-button
                    = hidden_field_tag :follow_to_id, user.id
                    %button{ class: (current_user.id == @user.id) ? "EdgeButton EdgeButton--secondary EdgeButton--small" : "EdgeButton EdgeButton--secondary EdgeButton--small third-party"}
                      フォローする
                  .following-button
                    = hidden_field_tag :follow_to_id, user.id
                    %button{ class: (current_user.id == @user.id) ? "EdgeButton EdgeButton--primary EdgeButton--small" : "EdgeButton EdgeButton--primary EdgeButton--small third-party"}
                      フォロー中
          .ProfileCard-userFields
            .ProfileNameTruncated
              .u-textTruncate.u-inlineBlock
                = link_to(user_path(user), class: "fullname") do
                  = user.nickname
            %span.screenname
              = link_to(user_path(user), class: "ProfileCard-screennameLink") do
                = "@" + user.name
            %p.ProfileCard-bio
              - if (user.biography.present?) and (user.biography.length > 65) then
                = user.biography[0..65] + "..."
              - elsif (user.biography.present?)
                = user.biography

app/views/layouts/_topbar.html.haml
.global-nav
  .container
    %i.fa.fa-twitter.center
    %ul.nav--global-actions
      %li#global-nav-home
        = link_to root_path, class: :active do
          %i.fa.fa-home
          %span.text ホーム
    = render "layouts/topbar_right_items"

app/views/layouts/_topbar_right_items.html.haml
%ul.nav--right-actions.pull-right
  %li
    %a{href: "/"}
      - if current_user.image_avatar.present? then
        = image_tag(current_user.image_avatar.url,size: "32x32", class: "avatar dropdown-toggle", id: "topbar-dropdown-toggle")
      - else
        = image_tag("default_profile_normal.png",size: "32x32", class: "avatar dropdown-toggle", id: "topbar-dropdown-toggle")
    .dropdown-menu#topbar-dropdown-menu
      .dropdown-caret
        .caret-wrapper
          .caret-outer
            %i.fa.fa-caret-up
          .caret-inner
            %i.fa.fa-caret-up
      %ul
        %li.DashUserDropdown-userInfo
          = link_to user_path(current_user), class: "DashUserDropdown-userInfoLink" do
            %b.fullname
              = current_user.nickname
            %p.name
              = "@" + current_user.name
        %li.dropdown-divider
        %li.current-user
          = link_to user_path(current_user) do
            %i.fa.fa-user-o
            プロフィール
        %li.dropdown-divider
        %li.signout-button
          = link_to "ログアウト", destroy_user_session_path, method: :delete
  %li
    %button.EdgeButton.EdgeButton--medium.EdgeButton--primary2#tweet-topbar-button
      ツイート

app/views/layouts/_tweets_stream.html.haml
.stream-container
  .stream
    %ol.stream-items
      - @tweets.each do |tweet|
        %li.stream-item
          .tweet.clearfix
            .context
              - if tweet.retweeted_by?(@retweeters_id) then
              - retweeted_user = tweet.recent_retweeted_user(@retweeters_id)
                .tweet-context.with-icn
                  %i.fa.fa-retweet
                  %span
                    =link_to(user_path(retweeted_user),class: "pretty-link") do
                      - if retweeted_user == current_user then
                        自分
                      - else
                        = retweeted_user.nickname
                    がリツイート
            .content
              .stream-item-header
                = link_to(user_path(tweet.user), class: "account-group") do
                  - if tweet.user.image_avatar.present? then
                    = image_tag(tweet.user.image_avatar.url, size: "48x48", class: "avatar")
                  - else
                    = image_tag("default_profile_normal.png",size: "48x48", class: "avatar")
                  %span.FullnameGroup
                    = tweet.user.nickname
                  %span.username
                    = "@" + tweet.user.name
                %span.time
                  = l tweet.created_at, format: :default
              .tweet-text-container
                %p.tweettext
                  = simple_format(h(tweet.tweet))
              .AdaptiveMediaOuterContainer
                - if tweet.image.present? then
                  = image_tag(tweet.image, class: "AdaptiveMedia is-square")
              .stream-item-footer
                .ProfileTweet-actionList
                  %div{ class: current_user.retweeting?(tweet) ? "ProfileTweet-action ProfileTweet-action--retweeting" : "ProfileTweet-action ProfileTweet-action--retweet"}
                    = hidden_field_tag :tweet_id, tweet.id
                    %button.ProfileTweet-actionButton.retweet
                      .Iconcontainer
                        %i.fa.fa-retweet
                      %span.ProfileTweet-actionCount
                        = tweet.retweet_count
                  - if tweet.user.id == current_user.id then
                    .ProfileTweet-action
                      = hidden_field_tag :tweet_id, tweet.id
                      %button.ProfileTweet-actionButton.delete
                        .Iconcontainer
                          %i.fa.fa-trash

app/views/layouts/_tweetstorm_modal.html.haml
.TweetStormDialog.modal-container
  .modal
    .modal-content
      .modal-header
        %h3.modal-title ツイートする
      .modal-body.clearfix
        .tweet-box-avatar
          - if current_user.image_avatar.present? then
            = image_tag(current_user.image_avatar.url,size: "32x32")
          - else
            = image_tag("default_profile_normal.png",size: "32x32")
        .tweet-box-content.clearfix
          = form_for(@tweet, html:{class: "clearfix"}) do |f|
            .editor-container
              = f.text_area :tweet, autofocus: false, class: "editor", maxlength: "240", placeholder: "いまどうしてる？"
            .tweetboxtoolbar
              .TweetBoxExtras
                .TweetBoxExtras-item
                  = f.file_field :image, autocomplete: "false",id: "tweet_image_modal"
                  %button#tweet-image-choose-modal-button
                    %i.fa.fa-picture-o
              .tweetboxtoolbar-tweetButton
                = f.submit "ツイート", class: "EdgeButton EdgeButton--medium EdgeButton--primary2"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TechExpertFinal
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield